FROM debian:12-slim

# https://serverfault.com/questions/949991/how-to-install-tzdata-on-a-ubuntu-docker-image
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
        ca-certificates \
        curl \
        gnupg \
        osm2pgsql \
        osmium-tool \
        gdal-bin \
        python3-psycopg2 \
        python3-yaml \
        python3-requests \
        unzip \
        postgresql-client \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean

ADD setup/openstreetmap-carto.style setup

RUN mkdir -p /openrailwaymap
WORKDIR /openrailwaymap

CMD ["sh", "docker-startup.sh", "import"]
