# Status
GET {{base_url}}/status
HTTP 200

# Replication timestamp
GET {{base_url}}/replication_timestamp
HTTP 200
[Asserts]
jsonpath "$.replication_timestamp" != null
jsonpath "$.import_timestamp" != null

# Facility request
GET {{base_url}}/facility
[QueryStringParams]
name: Berlin
HTTP 200
Content-Type: application/json
[Asserts]
jsonpath "$" count == 20
jsonpath "$[0].name" == "Berlin Hauptbahnhof (tief)"
jsonpath "$[1].name" == "S+U Hauptbahnhof"
jsonpath "$[2].name" == "Berlin Hauptbahnhof"
jsonpath "$[3].name" == "Hauptbahnhof"
jsonpath "$[4].name" == "Hauptbahnhof"
jsonpath "$[5].name" == "Berlin Hauptbahnhof Tunnel (S-Bahn)"
jsonpath "$[6].name" == "Berlin Südkreuz"
jsonpath "$[7].name" == "Südkreuz (Ringbahn)"
jsonpath "$[8].name" == "Südkreuz (Nord-Süd)"
jsonpath "$[9].name" == "Berlin-Spandau"
jsonpath "$[10].name" == "Spandau"
jsonpath "$[11].name" == "Ostbahnhof"
jsonpath "$[12].name" == "Berlin Ostbahnhof"
jsonpath "$[13].name" == "Berlin Gesundbrunnen"
jsonpath "$[14].name" == "Gesundbrunnen"
jsonpath "$[15].name" == "Berlin Alexanderplatz"
jsonpath "$[16].name" == "Alexanderplatz"
jsonpath "$[17].name" == "Berlin Friedrichstraße"
jsonpath "$[18].name" == "Ostkreuz"
jsonpath "$[19].name" == "S Friedrichstraße"

# Facility request with language
GET {{base_url}}/facility
[QueryStringParams]
name: Berlin Ostbahnhof
lang: en
HTTP 200
Content-Type: application/json
[Asserts]
jsonpath "$" count == 2
jsonpath "$[0].name" == "Ostbahnhof"
jsonpath "$[0].localized_name" == "Ostbahnhof"
jsonpath "$[1].name" == "Berlin Ostbahnhof"
jsonpath "$[1].localized_name" == "Berlin Eastern Station"

# Facility request with limit
GET {{base_url}}/facility
[QueryStringParams]
name: Berlin
limit: 5
HTTP 200
[Asserts]
jsonpath "$" count == 5

# Facility request with larger limit
GET {{base_url}}/facility
[QueryStringParams]
name: Berlin
limit: 25
HTTP 200
[Asserts]
jsonpath "$" count == 25

# Facility request too large limit
GET {{base_url}}/facility
[QueryStringParams]
name: Berlin
limit: 201
HTTP 422
[Asserts]
jsonpath "$.detail[0].msg" == "Input should be less than or equal to 200"

# Facility request too small limit
GET {{base_url}}/facility
[QueryStringParams]
name: Berlin
limit: 0
HTTP 422
[Asserts]
jsonpath "$.detail[0].msg" == "Input should be greater than or equal to 1"

# Facility request with hyphen
GET {{base_url}}/facility
[QueryStringParams]
name: Berlin-Spandau
HTTP 200
[Asserts]
jsonpath "$" count == 7
jsonpath "$[0].name" == "Berlin-Spandau"
jsonpath "$[1].name" == "Spandau"
jsonpath "$[2].name" == "Berlin-Spandau Johannesstift"
jsonpath "$[3].name" == "Berlin-Spandau Gbf"
jsonpath "$[4].name" == "Berlin-Spandau West"
jsonpath "$[5].name" == "Berlin-Spandau Mitte"
jsonpath "$[6].name" == "Berlin-Spandau Ost"

# Facility request with space
GET {{base_url}}/facility
[QueryStringParams]
name: Berlin Spandau
HTTP 200
[Asserts]
jsonpath "$" count == 7
jsonpath "$[0].name" == "Berlin-Spandau"
jsonpath "$[1].name" == "Spandau"
jsonpath "$[2].name" == "Berlin-Spandau Johannesstift"
jsonpath "$[3].name" == "Berlin-Spandau Gbf"
jsonpath "$[4].name" == "Berlin-Spandau West"
jsonpath "$[5].name" == "Berlin-Spandau Mitte"
jsonpath "$[6].name" == "Berlin-Spandau Ost"

# Facility request for Spandau
GET {{base_url}}/facility
[QueryStringParams]
name: Spandau
HTTP 200
[Asserts]
jsonpath "$" count == 9
jsonpath "$[0].name" == "Berlin-Spandau"
jsonpath "$[1].name" == "Spandau"
jsonpath "$[2].name" == "Berlin-Spandau Johannesstift"
jsonpath "$[3].name" == "Berlin-Spandau Gbf"
jsonpath "$[4].name" == "Rathaus Spandau"
jsonpath "$[5].name" == "Altstadt Spandau"
jsonpath "$[6].name" == "Berlin-Spandau West"
jsonpath "$[7].name" == "Berlin-Spandau Mitte"
jsonpath "$[8].name" == "Berlin-Spandau Ost"

# Facility request with diacritics
GET {{base_url}}/facility
[QueryStringParams]
name: Karl-Marx-Straße
HTTP 200
[Asserts]
jsonpath "$" count == 1
jsonpath "$[0].name" == "Karl-Marx-Straße"

# Facility request with name containing /
GET {{base_url}}/facility
[QueryStringParams]
name: Königsheideweg
HTTP 200
[Asserts]
jsonpath "$" count == 1
jsonpath "$[0].name" == "Sterndamm/Königsheideweg"

# Facility search for reference
GET {{base_url}}/facility
[QueryStringParams]
ref: BOKN
HTTP 200
[Asserts]
jsonpath "$" count == 1
jsonpath "$[0].name" == "Berlin Ostkreuz (Ringbahn-F)"
jsonpath "$[0].osm_ids" count == 1
jsonpath "$[0].osm_types" count == 1
jsonpath "$[0].osm_ids[0]" == 4746086763
jsonpath "$[0].osm_types[0]" == "N"

# Facility search for reference
GET {{base_url}}/facility
[QueryStringParams]
ref: BOKN
HTTP 200
[Asserts]
jsonpath "$" count == 1
jsonpath "$[0].name" == "Berlin Ostkreuz (Ringbahn-F)"

# Facility search by reference for yard (area)
GET {{base_url}}/facility
[QueryStringParams]
ref: BNO
HTTP 200
[Asserts]
jsonpath "$" count == 1
jsonpath "$[0].name" == "Berlin Nordost"

# Facility search for UIC reference
GET {{base_url}}/facility
[QueryStringParams]
ref: 8089028
HTTP 200
[Asserts]
jsonpath "$" count == 2
jsonpath "$[0].name" == "Ostkreuz"
jsonpath "$[1].name" == "Ostkreuz (Ringbahn)"

# Facility search for BVG reference
GET {{base_url}}/facility
[QueryStringParams]
ref: 309771
HTTP 200
[Asserts]
jsonpath "$" count == 1
jsonpath "$[0].name" == "Virchowstraße"
jsonpath "$[0].references.de-bvg" == "309770"

# Facility search for name or reference
GET {{base_url}}/facility
[QueryStringParams]
q: BOK
HTTP 200
[Asserts]
jsonpath "$" count == 4
jsonpath "$[0].name" == "Ostkreuz (Ringbahn)"
jsonpath "$[1].name" == "Rummelsburg"
jsonpath "$[2].name" == "S Frankfurter Allee"
jsonpath "$[3].name" == "Treptower Park"

# Facility search for name or reference
GET {{base_url}}/facility
[QueryStringParams]
q: Berlin Ostkreuz
HTTP 200
[Asserts]
jsonpath "$" count == 5
jsonpath "$[0].name" == "Ostkreuz"
jsonpath "$[1].name" == "Berlin Ostkreuz (Stadtbahn-F)"
jsonpath "$[2].name" == "Berlin Ostkreuz (Ringbahn-F)"
jsonpath "$[3].name" == "Berlin Ostkreuz (Ostbahn)"
jsonpath "$[4].name" == "Ostkreuz (Ringbahn)"

# Facility search for name or reference
GET {{base_url}}/facility
[QueryStringParams]
q: 8089028
HTTP 200
[Asserts]
jsonpath "$" count == 2
jsonpath "$[0].name" == "Ostkreuz"
jsonpath "$[1].name" == "Ostkreuz (Ringbahn)"

# Facility search for name or reference for grouped station
GET {{base_url}}/facility
[QueryStringParams]
q: Landsberger Allee
HTTP 200
[Asserts]
jsonpath "$" count == 6
jsonpath "$[0].name" == "Landsberger Allee/Petersburger Straße"
jsonpath "$[0].feature" == "tram_stop"
jsonpath "$[0].state" == "present"
jsonpath "$[0].rank" == 34
jsonpath "$[0].osm_ids" count == 4
jsonpath "$[0].osm_ids[0]" == 244129991
jsonpath "$[0].osm_ids[1]" == 271777826
jsonpath "$[0].osm_ids[2]" == 1679221136
jsonpath "$[0].osm_ids[3]" == 1787945074
jsonpath "$[0].osm_types" count == 4
jsonpath "$[3].railway_ref" == "BLST"
jsonpath "$[3].station" == "light_rail"
jsonpath "$[3].uic_ref" == "8089020"
jsonpath "$[3].operator[0]" == "DB InfraGO AG"
jsonpath "$[3].network[0]" == "Verkehrsverbund Berlin-Brandenburg"
jsonpath "$[3].wikidata[0]" == "Q800507"
jsonpath "$[3].wikipedia[0]" == "de:Bahnhof Berlin Landsberger Allee"

# Facility request missing required parameter
GET {{base_url}}/facility
HTTP 422
[Asserts]
jsonpath "$.detail.error" == "No argument with a search term provided."
jsonpath "$.detail.detail" == "Provide one of the following query parameters: q, name, ref"

# Facility request duplicated search parameters (1)
GET {{base_url}}/facility
[QueryStringParams]
q: 8089028
ref: test
HTTP 422
[Asserts]
jsonpath "$.detail.error" == "More than one argument with a search term provided."
jsonpath "$.detail.detail" == "Provide only one of the following query parameters: q, name, ref"

# Facility request duplicated search parameters (2)
GET {{base_url}}/facility
[QueryStringParams]
q: 8089028
ref: test
HTTP 422
[Asserts]
jsonpath "$.detail.error" == "More than one argument with a search term provided."
jsonpath "$.detail.detail" == "Provide only one of the following query parameters: q, name, ref"

# Facility request duplicated search parameters (3)
GET {{base_url}}/facility
[QueryStringParams]
q: test
name: test
ref: test
HTTP 422
[Asserts]
jsonpath "$.detail.error" == "More than one argument with a search term provided."
jsonpath "$.detail.detail" == "Provide only one of the following query parameters: q, name, ref"

# Facility request limit is not numeric
GET {{base_url}}/facility
[QueryStringParams]
limit: blabla
HTTP 422
[Asserts]
jsonpath "$.detail" count == 1
jsonpath "$.detail[0].msg" == "Input should be a valid integer, unable to parse string as an integer"

# Milestone request for line 6020 milestone 22.7
GET {{base_url}}/milestone
[QueryStringParams]
ref: 6020
position: 22.7
limit: 1
HTTP 200
[Asserts]
jsonpath "$" count == 1
jsonpath "$[0].line_ref" == "6020"
jsonpath "$[0].position" == "22.7"

# Milestone request too small limit
GET {{base_url}}/milestone
[QueryStringParams]
ref: 6020
position: 22.7
limit: 0
HTTP 422
[Asserts]
jsonpath "$.detail" count == 1
jsonpath "$.detail[0].msg" == "Input should be greater than or equal to 1"

# Milestone request too large limit
GET {{base_url}}/milestone
[QueryStringParams]
ref: 6020
position: 22.7
limit: 201
HTTP 422
[Asserts]
jsonpath "$.detail" count == 1
jsonpath "$.detail[0].msg" == "Input should be less than or equal to 200"

# Milestone request missing required ref and position parameters
GET {{base_url}}/milestone
HTTP 422
[Asserts]
jsonpath "$.detail" count == 2
jsonpath "$.detail[0].msg" == "Field required"
jsonpath "$.detail[1].msg" == "Field required"

# Milestone request with non-numeric arguments
GET {{base_url}}/milestone
[QueryStringParams]
ref: 6020
position: blabla
HTTP 422
[Asserts]
jsonpath "$.detail" count == 1
jsonpath "$.detail[0].msg" == "Input should be a valid number, unable to parse string as a number"

# Milestone request with non-numeric arguments
GET {{base_url}}/milestone
[QueryStringParams]
ref: 6020
position: 22.7
limit: blabla
HTTP 422
[Asserts]
jsonpath "$.detail" count == 1
jsonpath "$.detail[0].msg" == "Input should be a valid integer, unable to parse string as an integer"

# Route
GET {{base_url}}/route/64050
HTTP 200
Content-Type: application/geo+json
[Asserts]
jsonpath "$.id" == 64050
jsonpath "$.type" == "Feature"
jsonpath "$.properties.to" == "S Spindlersfeld"
jsonpath "$.properties.ref" == "S47"
jsonpath "$.properties.from" == "S Südkreuz"
jsonpath "$.properties.name" == "S47: S Südkreuz => S Spindlersfeld"
jsonpath "$.properties.type" == "light_rail"
jsonpath "$.properties.color" == "#BA8A4D"
jsonpath "$.properties.osm_id" == 64050
jsonpath "$.properties.operator" == "S-Bahn Berlin GmbH"
jsonpath "$.geometry.type" == "LineString"
jsonpath "$.geometry.coordinates" count > 0

# Non existing route
GET {{base_url}}/route/404
HTTP 404

# Route stops
GET {{base_url}}/route/stops/64050
HTTP 200
Content-Type: application/geo+json
[Asserts]
jsonpath "$.type" == "FeatureCollection"
jsonpath "$.features" count == 9
jsonpath "$.features[0].id" == 4946539230
jsonpath "$.features[0].type" == "Feature"
jsonpath "$.features[0].geometry.type" == "Point"
jsonpath "$.features[0].geometry.coordinates[0]" == 13.3654535
jsonpath "$.features[0].geometry.coordinates[1]" == 52.475174499
jsonpath "$.features[0].properties.name" == "Südkreuz"
jsonpath "$.features[0].properties.type" == "train"
jsonpath "$.features[0].properties.osm_id" == 4946539230

# Non existing route
GET {{base_url}}/route/stops/404
HTTP 200
Content-Type: application/geo+json
[Asserts]
jsonpath "$.type" == "FeatureCollection"
jsonpath "$.features" count == 0

# Non existing WikiData image
GET {{base_url}}/wikidata/Q0
HTTP 404
Content-Type: text/plain; charset=utf-8
[Asserts]
body == "Response from Wikidata API had status 400"

# WikiData image with metadata
GET {{base_url}}/wikidata/Q660045
HTTP 200
Content-Type: application/json
[Asserts]
jsonpath "$.file_name" == "2012-03-06_Berlin_Ostkreuz_vom_Treptower.jpg"
jsonpath "$.description" == "Berlin, <a href=\"https://en.wikipedia.org/wiki/Ostkreuz\" class=\"extiw\" title=\"en:Ostkreuz\">Ostkreuz</a>"
jsonpath "$.view_url" == "https://www.wikidata.org/wiki/Q660045#/media/File:2012-03-06_Berlin_Ostkreuz_vom_Treptower.jpg"
jsonpath "$.thumbnail_url" == "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/2012-03-06_Berlin_Ostkreuz_vom_Treptower.jpg/330px-2012-03-06_Berlin_Ostkreuz_vom_Treptower.jpg"
jsonpath "$.attribution" == "Wo st 01 / Wikimedia Commons"
jsonpath "$.license" == "CC BY-SA 3.0 de"
jsonpath "$.license_url" == "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en"

# WikiMedia image with metadata
GET {{base_url}}/wikimedia/U-Bahnhof%20Wuhletal.jpg
HTTP 200
Content-Type: application/json
[Asserts]
jsonpath "$.file_name" == "U-Bahnhof_Wuhletal.jpg"
jsonpath "$.description" == "U-Bahnhof Wuhletal (station du métro de Berlin, Allemagne)"
jsonpath "$.view_url" == "https://commons.wikimedia.org/wiki/File:U-Bahnhof%20Wuhletal.jpg#/media/File:U-Bahnhof_Wuhletal.jpg"
jsonpath "$.thumbnail_url" == "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/U-Bahnhof_Wuhletal.jpg/330px-U-Bahnhof_Wuhletal.jpg"
jsonpath "$.attribution" == "Molgreen, Own work"
jsonpath "$.license" == "CC BY-SA 4.0"
jsonpath "$.license_url" == "https://creativecommons.org/licenses/by-sa/4.0"

# Features
GET {{base_url}}/features/features.json
HTTP 200
Content-Type: application/json

# Feature does not exist
GET {{base_url}}/feature/layer-does-not-exist/source-does-not-exist/404
HTTP 404

# Signal box
GET {{base_url}}/feature/openrailwaymap_signals/signals_signal_boxes/way-485364317
HTTP 200
Content-Type: application/json
[Asserts]
jsonpath "$.note" == null
jsonpath "$.osm_id" == 485364317
jsonpath "$.osm_type" == "W"
jsonpath "$.feature" == "signal_box"
jsonpath "$.name" == "Biesdorfer Kreuz ESTW-A"
jsonpath "$.operator" == "DB InfraGO"
jsonpath "$.ref" == "BBIK"

# Catenary mast
GET {{base_url}}/feature/openrailwaymap_electrification/electrification_catenary/12329861010-mast
HTTP 200
Content-Type: application/json
[Asserts]
jsonpath "$.note" == null
jsonpath "$.description" == null
jsonpath "$.osm_id" == 12329861010
jsonpath "$.osm_type" == "N"
jsonpath "$.feature" == "mast"
jsonpath "$.supporting" == "cantilever"
jsonpath "$.position" count == 1
jsonpath "$.position[0]" == "11.6 (km)"
jsonpath "$.structure" == "lattice"

# Substation
GET {{base_url}}/feature/openrailwaymap_electrification/electrification_substation/62032242
HTTP 200
Content-Type: application/json
[Asserts]
jsonpath "$.note" == null
jsonpath "$.description" == null
jsonpath "$.osm_id" == 62032242
jsonpath "$.osm_type" == "W"
jsonpath "$.voltage" count == 2
jsonpath "$.voltage[0]" == 30000
jsonpath "$.voltage[1]" == 750

# Substation
GET {{base_url}}/feature/openrailwaymap_electrification/electrification_substation/320522867
HTTP 200
Content-Type: application/json
[Asserts]
jsonpath "$.note" == null
jsonpath "$.description" == null
jsonpath "$.osm_id" == 320522867
jsonpath "$.osm_type" == "W"
jsonpath "$.conversion" == "30 kV 50.00 Hz ⇒ 750 V ="

# Railway crossing
GET {{base_url}}/feature/openrailwaymap_standard/standard_railway_switch_ref/2101295628
HTTP 200
Content-Type: application/json
[Asserts]
jsonpath "$.note" == null
jsonpath "$.description" == null
jsonpath "$.osm_id" == 2101295628
jsonpath "$.osm_type" == "N"
jsonpath "$.railway" == "railway_crossing"

# Switch
GET {{base_url}}/feature/openrailwaymap_standard/standard_railway_switch_ref/2614563600
HTTP 200
Content-Type: application/json
[Asserts]
jsonpath "$.note" == null
jsonpath "$.description" == null
jsonpath "$.osm_id" == 2614563600
jsonpath "$.osm_type" == "N"
jsonpath "$.railway" == "switch"
jsonpath "$.ref" == "W3"
jsonpath "$.resetting" == true
jsonpath "$.local_operated" == true
jsonpath "$.type" == "default"

# Railway position
GET {{base_url}}/feature/high/railway_text_km/260827078-1
HTTP 200
Content-Type: application/json
[Asserts]
jsonpath "$.note" == "Bei den DB-Open-Data nicht genau erkennbar welcher von beiden der 3.255 und welcher der 3.256 ist, daher beide 3.256"
jsonpath "$.description" == null
jsonpath "$.osm_id" == 260827078
jsonpath "$.osm_type" == "N"
jsonpath "$.pos" == "3.2"
jsonpath "$.pos_exact" == "3.256"
jsonpath "$.railway" == "crossing"

# Stop position
GET {{base_url}}/feature/openrailwaymap_standard/standard_railway_stop_positions/1615531689
HTTP 200
Content-Type: application/json
[Asserts]
jsonpath "$.osm_id" == 1615531689
jsonpath "$.osm_type" == "N"
jsonpath "$.type" == "tram"
jsonpath "$.local_ref" == "14"
jsonpath "$.ref" == null
jsonpath "$.name" == "S+U Alexanderplatz/Dircksenstraße"
jsonpath "$.stop_position_routes" count == 4
jsonpath "$.stop_position_routes[0].label" == "Tram M2: S+U Alexanderplatz => Heinersdorf"
jsonpath "$.stop_position_routes[0].color" == "#33FF33"
jsonpath "$.stop_position_routes[0].route_id" == "28270"

# Station
GET {{base_url}}/feature/openrailwaymap_standard/standard_railway_text_stations/node-30217208-train-train-halt
HTTP 200
Content-Type: application/json
[Asserts]
jsonpath "$.note" count == 1
jsonpath "$.note[0]" == "Berlin Alexanderplatz (Fernbahngleise) ist von der S-Bahn-Station unabhängig und nur ein Haltepunkt, da es keine einzige Weiche gibt."
jsonpath "$.description" == null
jsonpath "$.station" == "train"
jsonpath "$.name" == "Berlin Alexanderplatz"
jsonpath "$.localized_name" == "Berlin Alexanderplatz"
jsonpath "$.yard_hump" == null
jsonpath "$.wikidata" count == 1
jsonpath "$.wikidata[0]" == "Q698497"
jsonpath "$.network" count == 1
jsonpath "$.network[0]" == "Verkehrsverbund Berlin-Brandenburg"
jsonpath "$.osm_id" count == 1
jsonpath "$.osm_id[0]" == 30217208
jsonpath "$.osm_type" count == 1
jsonpath "$.osm_type[0]" == "N"
jsonpath "$.references.uic" == "8089001"
jsonpath "$.references.station" == "53"
jsonpath "$.references.railway-ref" == "BALE"
jsonpath "$.wikipedia" count == 1
jsonpath "$.wikipedia[0]" == "de:Bahnhof Berlin Alexanderplatz"
jsonpath "$.state" == "present"
jsonpath "$.feature" == "halt"
jsonpath "$.station_routes" count == 38
jsonpath "$.station_routes[0].label" == "Tram M2: S+U Alexanderplatz => Heinersdorf"
jsonpath "$.station_routes[0].color" == "#33FF33"
jsonpath "$.station_routes[0].route_id" == "28270"
jsonpath "$.position" == null
jsonpath "$.operator" count == 1
jsonpath "$.operator[0]" == "DB InfraGO AG"

# Station with localized name
GET {{base_url}}/feature/openrailwaymap_standard/standard_railway_text_stations/node-30217208-train-train-halt
[QueryStringParams]
lang: ja
HTTP 200
Content-Type: application/json
[Asserts]
jsonpath "$.name" == "Berlin Alexanderplatz"
jsonpath "$.localized_name" == "ベルリン・アレクサンダー広場"

# Station with not defined localization
GET {{base_url}}/feature/openrailwaymap_standard/standard_railway_text_stations/node-30217208-train-train-halt
[QueryStringParams]
lang: nf
HTTP 200
Content-Type: application/json
[Asserts]
jsonpath "$.name" == "Berlin Alexanderplatz"
jsonpath "$.localized_name" == "Berlin Alexanderplatz"

# Stop area group
GET {{base_url}}/feature/openrailwaymap_standard/standard_railway_grouped_station_areas/7721002
[QueryStringParams]
lang: nf
HTTP 200
Content-Type: application/json
[Asserts]
jsonpath "$.osm_id" == 7721002
jsonpath "$.osm_type" == "R"
jsonpath "$.feature" == "station_area_group"

# Platform
GET {{base_url}}/feature/openrailwaymap_standard/standard_railway_platforms/relation-3637413
HTTP 200
Content-Type: application/json
[Asserts]
jsonpath "$.ref" count == 2
jsonpath "$.ref[0]" == "1"
jsonpath "$.ref[1]" == "2"
jsonpath "$.surface" == "paving_stones"
jsonpath "$.wheelchair" == true
jsonpath "$.lit" == true
jsonpath "$.shelter" == null
jsonpath "$.bin" == true
jsonpath "$.bench" == true
jsonpath "$.departures_board" == null
jsonpath "$.name" == "Berlin Alexanderplatz"
jsonpath "$.platform_routes" count == 10
jsonpath "$.platform_routes[0].label" == "RE2: Cottbus => Nauen"
jsonpath "$.platform_routes[0].color" == "#FFE600"
jsonpath "$.platform_routes[0].route_id" == "156479"
jsonpath "$.feature" == "platform"
jsonpath "$.height" == null
jsonpath "$.tactile_paving" == true
jsonpath "$.osm_id" == 3637413
jsonpath "$.osm_type" == "R"

# Platform edge
GET {{base_url}}/feature/openrailwaymap_standard/standard_railway_platform_edges/859918234
HTTP 200
Content-Type: application/json
[Asserts]
jsonpath "$.ref" == "2"
jsonpath "$.feature" == "platform_edge"
jsonpath "$.tactile_paving" == null
jsonpath "$.height" == null
jsonpath "$.length" > 152.2
jsonpath "$.length" < 152.3
jsonpath "$.osm_id" == 859918234
jsonpath "$.osm_type" == "W"

# POI (operator)
GET {{base_url}}/feature/openrailwaymap_operator/operator_railway_symbols/node-560099842
HTTP 200
Content-Type: application/json
[Asserts]
jsonpath "$.note" == null
jsonpath "$.osm_id" == 560099842
jsonpath "$.osm_type" == "N"
jsonpath "$.feature" == "general/owner-change"

# POI (infrastructure)
GET {{base_url}}/feature/openrailwaymap_standard/standard_railway_symbols/way-140374295
HTTP 200
Content-Type: application/json
[Asserts]
jsonpath "$.note" == "Container Terminal BeHaLa / City-GVZ Berlin"
jsonpath "$.description" == null
jsonpath "$.osm_id" == 140374295
jsonpath "$.osm_type" == "W"
jsonpath "$.feature" == "general/container-terminal"
jsonpath "$.name" == "Container Terminal BeHaLa / City-GVZ Berlin"
jsonpath "$.ref" == null

# Speed signal
GET {{base_url}}/feature/openrailwaymap_speed/speed_railway_signals/10719824502
HTTP 200
Content-Type: application/json
[Asserts]
jsonpath "$.note" == null
jsonpath "$.osm_id" == 10719824502
jsonpath "$.osm_type" == "N"
jsonpath "$.ref" == "08ZV819"
jsonpath "$.direction_both" == false
jsonpath "$.railway" == "signal"
jsonpath "$.feature0" == "de/zs3-sign-up-{40}"
jsonpath "$['railway:signal:position']" == "right"
jsonpath "$['railway:signal:speed_limit']" == "DE-ESO:zs3"
jsonpath "$['railway:signal:speed_limit:form']" == "sign"
jsonpath "$['railway:signal:speed_limit:speed']" count == 1
jsonpath "$['railway:signal:speed_limit:speed'][0]" == "40"
jsonpath "$['railway:signal:combined']" == "DE-ESO:ks"
jsonpath "$['railway:signal:combined:form']" == "light"
jsonpath "$['railway:signal:combined:height']" == "normal"
jsonpath "$['railway:signal:combined:function']" == "intermediate"
jsonpath "$['railway:signal:minor']" == "DE-ESO:sh1"
jsonpath "$['railway:signal:minor:form']" == "light"
jsonpath "$['railway:signal:traversable']" == "DE-ESO:mastschild_rot-weiss"
jsonpath "$['railway:signal:traversable:type']" == "written_default_speed;dictated_default_speed"

# Electrification signal
GET {{base_url}}/feature/openrailwaymap_electrification/electrification_signals/10720881143
HTTP 200
Content-Type: application/json
[Asserts]
jsonpath "$.note" == null
jsonpath "$.osm_id" == 10720881143
jsonpath "$.osm_type" == "N"
jsonpath "$.ref" == null
jsonpath "$.direction_both" == false
jsonpath "$.railway" == "signal"
jsonpath "$.feature0" == "de/el6-left"
jsonpath "$['railway:signal:position']" == "right"
jsonpath "$['railway:signal:electricity']" == "DE-ESO:el6"
jsonpath "$['railway:signal:electricity:type']" == "end_of_catenary"
jsonpath "$['railway:signal:electricity:form']" == "sign"
jsonpath "$['railway:signal:electricity:turn_direction']" == "left"

# Distant signal
GET {{base_url}}/feature/openrailwaymap_signals/signals_railway_signals/9351388537
HTTP 200
Content-Type: application/json
[Asserts]
jsonpath "$.note" == null
jsonpath "$.osm_id" == 9351388537
jsonpath "$.osm_type" == "N"
jsonpath "$.ref" == null
jsonpath "$.direction_both" == false
jsonpath "$.railway" == "signal"
jsonpath "$.feature0" == "de/zs2v-{T}"
jsonpath "$['railway:signal:distant']" == "DE-ESO:ks"
jsonpath "$['railway:signal:distant:form']" == "light"
jsonpath "$['railway:signal:distant:height']" == "normal"
jsonpath "$['railway:signal:distant:repeated']" == true
jsonpath "$['railway:signal:distant:states']" count == 2
jsonpath "$['railway:signal:distant:states'][0]" == "DE-ESO:ks1"
jsonpath "$['railway:signal:distant:states'][1]" == "DE-ESO:ks2"
jsonpath "$['railway:signal:position']" == "right"
jsonpath "$['railway:signal:route_distant']" == "DE-ESO:zs2v"
jsonpath "$['railway:signal:route_distant:form']" == "light"
jsonpath "$['railway:signal:route_distant:states']" count == 4
jsonpath "$['railway:signal:route_distant:states'][0]" == "R"
jsonpath "$['railway:signal:route_distant:states'][1]" == "S"
jsonpath "$['railway:signal:route_distant:states'][2]" == "T"
jsonpath "$['railway:signal:route_distant:states'][3]" == "off"
jsonpath "$['railway:signal:speed_limit_distant']" == "DE-ESO:zs3v"
jsonpath "$['railway:signal:speed_limit_distant:form']" == "light"
jsonpath "$['railway:signal:speed_limit_distant:speed']" count == 2
jsonpath "$['railway:signal:speed_limit_distant:speed'][0]" == "?"
jsonpath "$['railway:signal:speed_limit_distant:speed'][1]" == "off"

# Turntable
GET {{base_url}}/feature/openrailwaymap_standard/standard_railway_turntables/16109013
HTTP 200
Content-Type: application/json
[Asserts]
jsonpath "$.osm_id" == 16109013
jsonpath "$.osm_type" == "W"
jsonpath "$.feature" == "turntable"
jsonpath "$.diameter" == "23m"

# Entrance
GET {{base_url}}/feature/openrailwaymap_standard/standard_station_entrances/623932074
HTTP 200
Content-Type: application/json
[Asserts]
jsonpath "$.osm_id" == 623932074
jsonpath "$.osm_type" == "N"
jsonpath "$.type" == "subway"
jsonpath "$.name" == "Yorckstraße"
jsonpath "$.ref" == "E"

# Railway line
GET {{base_url}}/feature/high/railway_line_high/9933821-0
HTTP 200
Content-Type: application/json
[Asserts]
jsonpath "$.electrification_state" == "present"
jsonpath "$.feature" == "rail"
jsonpath "$.frequency" == 16.700000762939453
jsonpath "$.gauges" count == 1
jsonpath "$.gauges[0]" == "1435"
jsonpath "$.highspeed" == true
jsonpath "$.line_routes" count == 14
jsonpath "$.line_routes[0].color" == "#80004D"
jsonpath "$.line_routes[0].label" == "RE4: Falkenberg (Elster) => Stendal Hauptbahnhof"
jsonpath "$.line_routes[0].route_id" == "373229"
jsonpath "$.operator" count == 1
jsonpath "$.operator[0]" == "DB InfraGO AG"
jsonpath "$.osm_id" == 9933821
jsonpath "$.osm_type" == "W"
jsonpath "$.ref" == "6185"
jsonpath "$.name" == "Schnellfahrstrecke Oebisfelde–Spandau"
jsonpath "$.speed_label" == "140"
jsonpath "$.state" == "present"
jsonpath "$.train_protection" count == 2
jsonpath "$.train_protection[0]" == "lzb"
jsonpath "$.train_protection[1]" == "pzb"
jsonpath "$.usage" == "main"
jsonpath "$.voltage" == 15000
jsonpath "$.note" == null
jsonpath "$.description" == null

# No test for interlocking because no such features exist in the test data
